version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # Expose port for external access
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9999:8080"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
